version: 2

jobs:
  build:
    docker:
      - image: "debian:buster"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++ build-essential git'
      - run:
          name: Install CMAKE 
          command: 'apt-get update && apt-get install -y cmake'
      - run:
          name: Installing other dependencies
          command: 'apt-get update && apt-get install -y libssl-dev zlib1g-dev curl wget libpcre3-dev'
      - run:
          name: Downloading mysql
          command: 'wget -q https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-server_8.0.18-1debian10_amd64.deb-bundle.tar'
      - run:
          name: Installing mysql
          command: tar fpx mysql-server_8.0.18-1debian10_amd64.deb-bundle.tar && dpkg -i mysql-common_8.0.18-1debian10_amd64.deb && dpkg -i libmysqlclient21_8.0.18-1debian10_amd64.deb && dpkg -i libmysqlclient-dev_8.0.18-1debian10_amd64.deb && cp -rv /usr/include/mysql/* /usr/local/include/
      - run:
          name: Cloning aegis
          command: 'git clone --branch master https://github.com/zeroxs/aegis.cpp'
      - run:
          name: Checking out and building aegis deps
          command: 'cd aegis.cpp && git submodule init lib/asio && git submodule init lib/json && git submodule init lib/spdlog &&  git submodule init lib/websocketpp && git submodule update && ./install-deps.sh'
      - run:
          name: Creating aegis build files
          command: 'cmake  -Haegis.cpp -Baegis.cpp/build'
      - run:
          name: Building aegis
          command: 'cmake --build aegis.cpp/build'
      - run:
          name: Installing aegis
          command: 'cd aegis.cpp/build && make install'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'

